# Generated by Django 3.0.3 on 2020-03-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20200329_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='no_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
